### ISSUE TITLE
looking forward to the code release

### ISSUE THREAD

**Issue by turboxin** [happinesslz/TANet#1]
hi, when do you expect the code would be released, looking forward to it~

**Comment by 94happy** [comment]
I plan to release my code based on the  version of PointPillars~(https://github.com/nutonomy/second.pytorch) before 2020.1.18 .  For convenience, I also  add my TANet to the newest second.pytorch~(https://github.com/traveller59/second.pytorch) before AAAI-2020 conference.  After that, I will  consider  to further improve the inference speed.

**Comment by turboxin** [comment]
Thank you, closing this issue
