### ISSUE TITLE
Train with my own dataset

### ISSUE THREAD

**Issue by JingyaLiu** [happinesslz/TANet#10]
Hi, 

Thanks for the nice work! Do you have any suggestions for how should I modify my own dataset to use TANet?

**Comment by happinesslz** [comment]
@JingyaLiu  First, you need convert  your own data format to KITTI format. You can refer [data_precess](https://github.com/happinesslz/TANet/tree/master/pointpillars_with_TANet/second/data) .Then use " similar process with TANet to train your model.

**Comment by happinesslz** [comment]
@JingyaLiu First, you need convert your own data format to KITTI format. You can refer [data_process](https://github.com/happinesslz/TANet/tree/master/pointpillars_with_TANet/second/data) .Then use " similar operations with TANet to train your model.
