### ISSUE TITLE
How to train and test on own dataset?

### ISSUE THREAD

**Issue by Reeshark** [happinesslz/TANet#11]
How to train and test on own dataset? Do we have to change some parameters (such as point cloud range, voxel size)?

**Comment by happinesslz** [comment]
@Reeshark  If your dataset contains images and can provide the camera projection matrix. Choose  the points that are projected onto the image. And find the point  range which can contain all selected point clouds (maybe you need  traverse the whole dataset). For voxel size, make sure  that ` point cloud range // voxel size ` is equal a integer (I suggest  that the integer is 2^k if you want to sub-sampling the feature map in RPN).

**Comment by Reeshark** [comment]
Thanks for your reply.
I have some extra questions:
1.why do you use this operation on line 147 in preprocess.py (gt_boxes=box_np_ops.box_camera_to_lidar(gt_boxes, rect, Trv2c))?
The x,y,z of gt_boxes are from KITTI labels, they are already the 3D position, and why do you use rect and Trv2c to project points again?
2. If we train and test TANet on own dataset, what's the influence without db_sampler?
