### ISSUE TITLE
Result ststistics on Nuscenes dataset

### ISSUE THREAD

**Issue by chowkamlee81** [happinesslz/TANet#13]
Did you performed training and evaluation on Nuscenes dataset..? KIndly help

**Comment by happinesslz** [comment]
Yes. Please refer [run_lowa_all_nuscenes_ta_module.sh](https://github.com/happinesslz/TANet/blob/master/second.pytorch_with_TANet/second/run_lowa_all_nuscenes_ta_module.sh) and the  [README](https://github.com/happinesslz/TANet/blob/master/README.md).

**Comment by yukke42** [comment]
@happinesslz Cloud you share the results of PointPillars with / without TANet on nuScenes dataset?

**Comment by happinesslz** [comment]
Sorry, Now I don't find the results. But I remember  the method with only TA module (without PSA ) can bring the improvement with the mAP of about 3% than without TA module for PointPillars. You could have a try.

**Comment by yukke42** [comment]
Thank you! I will have a try.
