### ISSUE TITLE
Some question about attention module

### ISSUE THREAD

**Issue by leoncesc** [happinesslz/TANet#14]
Thanks for your sharing this great work. I have some question about the attention module.
First, the channel-wise attention operation, I think, tends to select the maximum of` [x, y, z, intensity]`.
Second, the point wise attention operation tends to select the farthest point in each voxel.
So these operations seems to have any instinct sense. 
If I have mis-understood the idea of attention, please tell me.
Thanks again.

**Comment by happinesslz** [comment]
@leoncesc  Maybe you should regard the input as the feature of point cloud. So the attention module can help the network select the key feature, and the feature contains x,y,z,intensity, and even  deeper feature. 
In fact, the dimension of the input is 9 not 4-dim([x, y, z, intensity] ), which is same with PointPillars. Hope  it  helps you!
