### ISSUE TITLE
how to load a trained model

### ISSUE THREAD

**Issue by Seasons2020** [happinesslz/TANet#19]
anyone know how to load a trained model?I am a baginner , i am confused with loading trained model,then running the model on myself data for days? It is hard for me to do this.Can you tell in details?

**Comment by happinesslz** [comment]
@Seasons2020  you can run the evaluation by the following commond:
`CUDA_VISIBLE_DEVICES=0 python ./pytorch/train.py evaluate --config_path=./configs/tanet/car/xyres_16.proto --model_dir=/mnt/data2/TANet/pointpillars/second/train_16_car_tanet`, or please refer  [run_car_16_tanet.sh](https://github.com/happinesslz/TANet/blob/2d4b2ab99b8e57c03671b0f1531eab7dca8f3c1f/pointpillars_with_TANet/second/run_car_16_tanet.sh#L7)
