### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by WSTao** [happinesslz/TANet#2]
Hi, can you provide a trained model，thanks

**Comment by happinesslz** [comment]
Trained model is available (Note: Please use the newest code!):
Baiduyunpan:  
Link:  https://pan.baidu.com/s/1TfeYpkyRORPFLktS9REc2g  
Password: 5fe1

**Comment by happinesslz** [comment]
@WSTao  
Trained model is available (Note: Please use the newest code!):
Baiduyunpan:
Link: https://pan.baidu.com/s/1TfeYpkyRORPFLktS9REc2g
Password: 5fe1

**Comment by jhultman** [comment]
@happinesslz Can you post link to Google Drive / Dropbox? Even with the password, it seems we need to register pan baidu account which may require China mainland phone number. Thanks!

**Comment by happinesslz** [comment]
@jhultman  Ok! Thanks for you suggestion!  I will register Google Drive and add the link to README.

**Comment by happinesslz** [comment]
@jhultman  
Google Driver Link: https://drive.google.com/drive/folders/1jSuQy5svfkDBw_4JszSzmIp9tpH1Ox7f

**Comment by jhultman** [comment]
@happinesslz Thanks so much!
