### ISSUE TITLE
Visualization of the inference results in the pointcloud 

### ISSUE THREAD

**Issue by aldipiroli** [happinesslz/TANet#20]
Hello @happinesslz and thanks for the great work. I was wondering how can I reproduce the visualization of the 3d bounding boxes on the pointcloud itself like in the image (on the right).
![image](https://user-images.githubusercontent.com/25965474/117634466-39959780-b17f-11eb-95fc-65e6fdc6df49.png)
 
Is there a code in the repo, or is it extra ? Moreover, can the visualization be done with the KittiViewer web ? 

Best,
Aldi

**Comment by abhigoku10** [comment]
@aldipiroli  any update on this thread ? it would be helpful

**Comment by weemeng** [comment]
@abhigoku10 @aldipiroli any way to visualise the results on your end?

**Comment by abhigoku10** [comment]
@abhigoku10 i just used vedo for viz!!

**Comment by weemeng** [comment]
@abhigoku10 perfect! do you have a link to this Vedo for Viz? I can't seem to find any info on this in particular through Google
