### ISSUE TITLE
Question about the accuracy of the Ped&Cyc model

### ISSUE THREAD

**Issue by Treemann** [happinesslz/TANet#3]
Hi @happinesslz ,
Thanks for your contribution!
I try to reproduce the results on Car and Ped&Cyc with your default configurations, only to find there  is a gap on the accuracy of Ped&Cyc while the accuracy of Car is not bad.
Could you explain why?
|Config|Claimed AP|Reproduced AP|
|-|-|-|
|Car|Car 3d:   88.17, 77.75, 75.31|Car 3d: 88.41, 77.84, 75.84|
|Ped&Cyc|Ped 3d:  71.04, 64.20, 59.11<br>Cyc 3d:   85.21, 65.29, 61.57|Ped 3d: 68.73, 62.96, 56.60<br>Cyc 3d: 80.11, 60.74, 56.18|

**Comment by happinesslz** [comment]
For Ped&Cyc, we train our model (refine_weight=5 ) in Titan Xp or Titan V in the released code. 
First, the best performance is not the final model ckpt,  you need choose the model of the intermediate process.
In addition, you can modify "steps: 371200" instead of "steps: 296960" in xyres_16.proto for better performance.

**Comment by Treemann** [comment]
According to your defualt configuration: steps=371200, batch_size=2 and refine_weight=2.
I'll train with refine_weight=5 for verification.
Thanks!

**Comment by LZDSJTU** [comment]
> According to your defualt configuration: steps=371200, batch_size=2 and refine_weight=2.
> I'll train with refine_weight=5 for verification.
> Thanks!

Hi, have you reproduced the claimed result? Which parameter did you modify?

Thank you very much.

**Comment by ldtho** [comment]
@Treemann @happinesslz I tried to reproduce your result but the Ped&Cyc mAP is not as claimed. And how did you add noise points to the objects as well? :)
Thank you so much.

**Comment by Treemann** [comment]
> > According to your defualt configuration: steps=371200, batch_size=2 and refine_weight=2.
> > I'll train with refine_weight=5 for verification.
> > Thanks!
> 
> Hi, have you reproduced the claimed result? Which parameter did you modify?
> 
> Thank you very much.

I haven't reproduced the claimed result.
