### ISSUE TITLE
multiclass object detection

### ISSUE THREAD

**Issue by jaylee7** [happinesslz/TANet#4]
Hi there,
Is there any config file for multiclass object detection?

**Comment by happinesslz** [comment]
We will provide  multiclass object detection in NuScenes dataset using tanet soon. In fact, on KITTI, we train two-class  object detection  at the same time. Or you can refer the config of SEOND[https://github.com/traveller59/second.pytorch/blob/master/second/configs/all.fhd.config](url)

**Comment by happinesslz** [comment]
@jaylee7   We will provide  multiclass object detection in NuScenes dataset using tanet soon. In fact, on KITTI, we train two-class  object detection  at the same time. Or you can refer the config of SEOND[https://github.com/traveller59/second.pytorch/blob/master/second/configs/all.fhd.config](url)

**Comment by happinesslz** [comment]
@jaylee7 We will provide multiclass object detection in NuScenes dataset using tanet soon. In fact, on KITTI, we train two-class object detection at the same time. Or you can refer the config of SECONDhttps://github.com/traveller59/second.pytorch/blob/master/second/configs/all.fhd.config

**Comment by happinesslz** [comment]
@jaylee7 We will provide multiclass object detection in NuScenes dataset using tanet soon. In fact, on KITTI, we train two-class object detection at the same time. Or you can refer the config of SECOND [https://github.com/traveller59/second.pytorch/blob/master/second/configs/all.fhd.config]

**Comment by happinesslz** [comment]
@jaylee7 We will provide multiclass object detection in NuScenes dataset using tanet soon. In fact, on KITTI, we train two-class object detection at the same time. Or you can refer the config of SECOND [https://github.com/traveller59/second.pytorch/blob/master/second/configs/all.fhd.config](url)

**Comment by happinesslz** [comment]
@jaylee7 We will provide multiclass object detection in NuScenes dataset using tanet soon. In fact, on KITTI, we train two-class object detection at the same time. Or you can refer the config of SECOND [all.fhd.config](https://github.com/traveller59/second.pytorch/blob/master/second/configs/all.fhd.config)
