### ISSUE TITLE
cannot import name 'box_ops_cc' from 'second.core'

### ISSUE THREAD

**Issue by insigh** [happinesslz/TANet#6]
Traceback (most recent call last):
  File "/home/olap/model_test/python/TANet/pointpillars_with_TANet/second/core/box_np_ops.py", line 10, in <module>
    ```

**> from second.core import box_ops_cc
> ImportError: cannot import name 'box_ops_cc' from 'second.core'** 

```(/home/olap/model_test/python/TANet/pointpillars_with_TANet/second/core/__init__.py)

**Comment by happinesslz** [comment]
@insigh  Maybe you need Add TANet/pointpillars_with_TANet/ to your PYTHONPATH.
