### ISSUE TITLE
Evaluation on TANet for PointPillars

### ISSUE THREAD

**Issue by MYSystemLogistics** [happinesslz/TANet#8]
Hi @happinesslz, 

How can I run the evaluation on TANet for PointPillars for trained models?

I downloaded your trained models from Google Drive and I just want to run the evaluation.
Is the following command correct?:
`python ./pytorch/train.py train --config_path=./configs/car.config --model_dir=./models/car_trained`

Thank you for your attention.

**Comment by happinesslz** [comment]
For example, for evaluating trained model on ped&cyc,  you could follow the command:
**CUDA_VISIBLE_DEVICES=0 python ./pytorch/train.py evaluate --config_path=./configs/tanet/ped_cycle/xyres_16.proto --model_dir=Model_Path** 

Or you could refer the script file in [run_ped_cycle_16_tanet.sh](https://github.com/happinesslz/TANet/blob/master/pointpillars_with_TANet/second/run_ped_cycle_16_tanet.sh) for training and evaluation.

**Comment by happinesslz** [comment]
@MYSystemLogistics  For example, for evaluating trained model on ped&cyc, you could follow the command:
`CUDA_VISIBLE_DEVICES=0 python ./pytorch/train.py evaluate --config_path=./configs/tanet/ped_cycle/xyres_16.proto --model_dir=Model_Path`

Or you could refer the script file in run_ped_cycle_16_tanet.sh for training and evaluation.

**Comment by happinesslz** [comment]
@MYSystemLogistics   
For example, for evaluating trained model on ped&cyc, you could follow the command:
`CUDA_VISIBLE_DEVICES=0` python ./pytorch/train.py evaluate --config_path=./configs/tanet/ped_cycle/xyres_16.proto --model_dir=Model_Path`

Or you could refer the script file in [run_ped_cycle_16_tanet.sh](https://github.com/happinesslz/TANet/blob/master/pointpillars_with_TANet/second/run_ped_cycle_16_tanet.sh) for training and evaluation.

**Comment by MYSystemLogistics** [comment]
After running the following command:
`CUDA_VISIBLE_DEVICES=0 python ./pytorch/train.py evaluate --config_path=./configs/tanet/ped_cycle/xyres_16.proto --model_dir=./models/ped-cyc_trained`

I get this error:
```
Traceback (most recent call last):
  File "./pytorch/train.py", line 14, in <module>
    import torchplus
ModuleNotFoundError: No module named 'torchplus'
```
How can I solve this?

**Comment by happinesslz** [comment]
@MYSystemLogistics  Add TANet/pointpillars_with_TANet/ to your PYTHONPATH.
