### ISSUE TITLE
Could you provide visualization codes?

### ISSUE THREAD

**Issue by Reeshark** [happinesslz/TANet#9]
Thanks for your useful project. How can we visual result such as the image of comparison between TANet and PointPillars on Visualization part?  Could you provide visualization codes?

**Comment by happinesslz** [comment]
@Reeshark  First, after the maxpoling operation,  save the features  which are extracted with TA module. Then you can obation  the feature map with the shape of H*W*C.  Sum the feature map along the dimension of "channel",  leading to the shape of H*W*C. Finally, plot its heatmap.
